// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4EtjS61Zdfp2urqc9bhoh3co9aFJy7Cg',
    appId: '1:38595658838:web:1cf51cb6708005f758e7f7',
    messagingSenderId: '38595658838',
    projectId: 'dashdish-c0189',
    authDomain: 'dashdish-c0189.firebaseapp.com',
    storageBucket: 'dashdish-c0189.firebasestorage.app',
    measurementId: 'G-M8Q4ZJR048',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPmv9geHK5C03wEt-ZoTCoIIb-eAKKOpE',
    appId: '1:38595658838:android:7390b3cc7dd2442c58e7f7',
    messagingSenderId: '38595658838',
    projectId: 'dashdish-c0189',
    storageBucket: 'dashdish-c0189.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1SQRycA0VApxTRgUKPg9gkWSqa1Q5pZg',
    appId: '1:38595658838:ios:97d38098a84df01558e7f7',
    messagingSenderId: '38595658838',
    projectId: 'dashdish-c0189',
    storageBucket: 'dashdish-c0189.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1SQRycA0VApxTRgUKPg9gkWSqa1Q5pZg',
    appId: '1:38595658838:ios:97d38098a84df01558e7f7',
    messagingSenderId: '38595658838',
    projectId: 'dashdish-c0189',
    storageBucket: 'dashdish-c0189.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4EtjS61Zdfp2urqc9bhoh3co9aFJy7Cg',
    appId: '1:38595658838:web:ce216698d62d941458e7f7',
    messagingSenderId: '38595658838',
    projectId: 'dashdish-c0189',
    authDomain: 'dashdish-c0189.firebaseapp.com',
    storageBucket: 'dashdish-c0189.firebasestorage.app',
    measurementId: 'G-2Y5WZ125TT',
  );
}
